version: '3.8'

services:
  api:
    build: .
    container_name: volunteer_vision_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${API_PORT};https://+:${API_PORT_HTTPS}
    ports:
      - "5458:5458"
      - "5459:5459"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:latest
    container_name: volunteer_vision_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
