version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: volunteer_vision_api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${API_PORT};https://+:${API_PORT_HTTPS}
    ports:
      - "${API_PORT}:${API_PORT}" # HTTP
      - "${API_PORT_HTTPS}:${API_PORT_HTTPS}" # HTTPS
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:latest
    container_name: volunteer_vision_database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
