version: '3.8'

services:
  api:
    build: .
    container_name: volunteer_vision_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5458;https://+:5459
    ports:
      - "5458:5458"
      - "5459:5459"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=volunteer_vision_admin
      - POSTGRES_PASSWORD=volunteer_vision_admin_password
      - POSTGRES_DB=volunteer_vision_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
