version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=volunteer_vision_admin
      - POSTGRES_PASSWORD=volunteer_vision_admin_password
      - POSTGRES_DB=volunteer_vision_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
